# Encoding Technique 1: Ordinal Encoding

**Dataset:** `Loan_Default.csv`

**When to use:** For **ordinal** (ordered) categorical features. The encoder assigns an integer to each category, preserving the natural rank order.

**Key concept:** The `age` column (`<25`, `25-34`, `35-44`, `45-54`, `55-64`, `>64`) is a perfect example — it has a natural, meaningful order.

---

### Step 1: Setup & Data Loading

In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

# Load data
df = pd.read_csv('../../data/raw/Loan_Default.csv')
df.drop(['ID', 'year'], axis=1, inplace=True)

print(f'Starting shape: {df.shape}')
df.head()

Starting shape: (148670, 32)

,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,116500,NaN,...,EXP,758,CIB,25-34,to_inst,98.728814,south,direct,1,45.0
1,cf,Male,nopre,type2,p1,l1,nopc,b/c,206500,NaN,...,EQUI,552,EXP,55-64,to_inst,NaN,North,direct,1,NaN
2,cf,Male,pre,type1,p1,l1,nopc,nob/c,406500,4.56,...,EXP,834,CIB,35-44,to_inst,80.019685,south,direct,0,46.0
3,cf,Male,nopre,type1,p4,l1,nopc,nob/c,456500,4.25,...,EXP,587,CIB,45-54,not_inst,69.376900,North,direct,0,42.0
4,cf,Joint,pre,type1,p1,l1,nopc,nob/c,696500,4.00,...,CRIF,602,EXP,25-34,not_inst,91.886544,North,direct,0,39.0

### Step 2: Identify Ordinal Feature

We identify 'age' as the ordinal feature. In a real-world scenario, you would explicitly define the order (e.g., `<25` < `25-34` < ...) to ensure the encoder doesn't just use alphabetical order.

In [2]:
Ordinal_features = ['age']

### Step 3: Apply Ordinal Encoding

The `OrdinalEncoder` from scikit-learn converts categorical labels into integer codes.

In [3]:
df_ordinal = df.copy()

enc = OrdinalEncoder()
df_ordinal[Ordinal_features] = enc.fit_transform(df_ordinal[Ordinal_features])
df_ordinal.head()

,loan_limit,Gender,approv_in_adv,loan_type,loan_purpose,Credit_Worthiness,open_credit,business_or_commercial,loan_amount,rate_of_interest,...,credit_type,Credit_Score,co-applicant_credit_type,age,submission_of_application,LTV,Region,Security_Type,Status,dtir1
0,cf,Sex Not Available,nopre,type1,p1,l1,nopc,nob/c,116500,NaN,...,EXP,758,CIB,0.0,to_inst,98.728814,south,direct,1,45.0
1,cf,Male,nopre,type2,p1,l1,nopc,b/c,206500,NaN,...,EQUI,552,EXP,3.0,to_inst,NaN,North,direct,1,NaN
2,cf,Male,pre,type1,p1,l1,nopc,nob/c,406500,4.56,...,EXP,834,CIB,1.0,to_inst,80.019685,south,direct,0,46.0
3,cf,Male,nopre,type1,p4,l1,nopc,nob/c,456500,4.25,...,EXP,587,CIB,2.0,not_inst,69.376900,North,direct,0,42.0
4,cf,Joint,pre,type1,p1,l1,nopc,nob/c,696500,4.00,...,CRIF,602,EXP,0.0,not_inst,91.886544,North,direct,0,39.0

### Step 4: Verify the Result

The `age` column should now contain floats representing the encoded age brackets.

In [4]:
print(df_ordinal['age'].value_counts())
print(f'\nData type of age column: {df_ordinal["age"].dtype}')

age
2.0    34720
1.0    32818
3.0    32534
4.0    20744
0.0    19142
6.0     7175
5.0     1337
Name: count, dtype: int64

Data type of age column: float64